name: Sync Wiki
on:
  push:
    branches: [main]
    paths:
      - wiki_docs/**
      - .github/workflows/sync-wiki.yml
  repository_dispatch:
    types: [wiki]
  gollum:

concurrency:
  group: sync-wiki

jobs:
  sync-to-wiki:
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Sync Repo Folder to Wiki
        uses: newrelic/wiki-sync-action@main
        with:
          source: wiki_docs
          destination: wiki
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
  
  sync-from-wiki:
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Sync Repo Folder from Wiki
        uses: newrelic/wiki-sync-action@main
        with:
          source: wiki
          destination: wiki_docs
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
